import { NextResponse } from "next/server";
import { getGithubProviderToken } from "@/lib/auth";
import { createGitHubPullRequest, fetchGitHubSourceFiles } from "@/lib/github";
import { getScan } from "@/lib/scans";
import { remediateFiles } from "@/lib/scanner/remediation";
import { env } from "@/lib/env";
import type { RemediationPullRequest } from "@/lib/types";
import { remediateRequestSchema } from "@/lib/validation";

export const runtime = "nodejs";

export async function POST(request: Request) {
  const body = await request.json().catch(() => null);
  const parsed = remediateRequestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid remediation request" }, { status: 400 });
  }

  const scan = await getScan(parsed.data.hash);
  if (!scan) return NextResponse.json({ error: "Scan not found" }, { status: 404 });
  if (!scan.repoUrl) return NextResponse.json({ error: "Connect a GitHub repo before remediation" }, { status: 400 });
  if (!env.GEMINI_API_KEY) return NextResponse.json({ error: "GEMINI_API_KEY is required to create code fixes" }, { status: 400 });

  const token = await getGithubProviderToken();
  if (!token) return NextResponse.json({ error: "Connect GitHub before creating pull requests" }, { status: 403 });

  const files = await fetchGitHubSourceFiles(scan.repoUrl, token);
  if (!files.length) return NextResponse.json({ error: "Could not read source files from the connected GitHub repo" }, { status: 400 });

  const selectedIndexes = parsed.data.findingIndexes ? new Set(parsed.data.findingIndexes) : null;
  const selectedIds = parsed.data.findingIds ? new Set(parsed.data.findingIds) : null;
  const findings = scan.findings.filter((finding, index) => {
    if (!finding.autoFixable) return false;
    if (selectedIndexes) return selectedIndexes.has(index);
    if (selectedIds) return selectedIds.has(finding.id);
    return true;
  });
  if (!findings.length) return NextResponse.json({ error: "No auto-fixable findings selected" }, { status: 400 });

  const pullRequests: RemediationPullRequest[] = [];

  for (const finding of findings) {
    try {
      const results = await remediateFiles(files, [finding], scan.stack);
      const changedResults = results.filter((result) => result.fixed !== result.original);
      if (!changedResults.length) {
        pullRequests.push({ finding, results, error: "Gemini did not produce a code change for this finding." });
        continue;
      }

      const pullRequest = await createGitHubPullRequest({
        repoUrl: scan.repoUrl,
        accessToken: token,
        title: `Fix Redline finding: ${finding.title}`,
        branchPrefix: `redline/${scan.hash}/${finding.id}`,
        body: [
          `Fixes Redline finding \`${finding.id}\`: ${finding.title}`,
          "",
          `Severity: ${finding.severity}`,
          "",
          finding.what,
          "",
          "Generated by Redline using Gemini. Review and test before merging."
        ].join("\n"),
        files: changedResults.map((result) => ({
          path: result.filePath,
          sha: result.sha,
          fixed: result.fixed
        }))
      });

      pullRequests.push({
        finding,
        results,
        pullRequestUrl: pullRequest.url,
        pullRequestNumber: pullRequest.number,
        branchName: pullRequest.branchName
      });
    } catch (error) {
      pullRequests.push({
        finding,
        results: [],
        error: error instanceof Error ? error.message : "Could not create a pull request for this finding"
      });
    }
  }

  return NextResponse.json({ pullRequests });
}
